feat: Add main search page
andres-acc/rick-and-morty-w-challenge pull request #11
Opened 2023-03-13 23:28 UTC by andres-acc

## Summary
* Add main search page
* Add colors
* Add bacground images

## Preview
![Screen Shot 2023-03-13 at 6 23 31 PM](https://user-images.githubusercontent.com/102995236/224854263-37a5fc3c-de4f-4a55-90a9-cebb996c67d5.png)

## Trello Card
https://trello.com/c/smrt5zJX

2023-03-13 23:33 UTC, YgRamos9 commented on src/app/components/result-list/character-result-box/character-result-box.component.ts
> +import { Status } from '../../../helpers/enums/status.enum';
- use absolute path please

2023-03-13 23:33 UTC, YgRamos9 commented on src/app/pages/search-character/search-character.component.scss
> +      background: url('../../../assets/images/main-background.png');
- you could also use

```suggestion
      background: url('/assets/images/main-background.png');
```

2023-03-13 23:34 UTC, YgRamos9 approved these changes

2023-03-14 19:48 UTC, miguelhenaoa requested changes

2023-03-14 19:48 UTC, miguelhenaoa commented on src/app/pages/search-character/search-character.component.scss
> +      top: 40vh;
sort

2023-03-14 19:48 UTC, miguelhenaoa commented on src/app/pages/search-character/search-character.module.ts
> +import { BigInputModule } from 'src/app/components/big-input/big-input.module';
Move above

2023-03-16 20:33 UTC, miguelhenaoa approved these changes

2023-03-17 12:57 UTC, merged