Feat/aa/main search get characters
andres-acc/rick-and-morty-w-challenge pull request #15
Opened 2023-03-17 19:31 UTC by andres-acc

## Summary
* Add pipes to the filter character service
* Refactor some failing components
* Implement filtered search

## Preview
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/102995236/226001836-31171b6a-d5c6-44e0-8b51-00ca6194f7ba.gif)

## Trello card
https://trello.com/c/AZxFs3dS

2023-03-17 22:34 UTC, CarlZac approved these changes

2023-03-22 20:34 UTC, miguelhenaoa requested changes

2023-03-22 20:34 UTC, miguelhenaoa commented on src/app/pages/search-character/search-character.component.html
> +    </app-big-input>
In same line

2023-03-22 20:34 UTC, miguelhenaoa commented on src/app/pages/search-character/search-character.component.ts
> +    }
semicolon

2023-03-22 20:34 UTC, miguelhenaoa commented on src/app/pages/search-character/search-character.component.ts
> +      })
same

2023-03-24 14:56 UTC, miguelhenaoa approved these changes

2023-03-24 15:02 UTC, miguelhenaoa approved these changes

2023-03-24 16:04 UTC, merged