feat(Footer): implements design
andres-acc/rick-and-morty-w-challenge pull request #16
Opened 2023-03-22 17:32 UTC by YgRamos9

## Summary

- add typography
- add footer section
- add fonts mixies
- add icons

## Screenshots

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/107204529/226989324-a1e2473c-ae16-41f8-ba41-678f59135b67.png">

## Known Issues

- links are not added

## Trello Card

- https://trello.com/c/jCZcsjaS/4-layout-create-main-search-footer-component

2023-03-22 18:24 UTC, andres-acc requested changes

2023-03-22 18:24 UTC, andres-acc commented on src/app/components/footer/footer.component.html
> +<section class="footer-section">
Use the footer tag.
```suggestion
<footer class="footer-section">
```

2023-03-22 18:24 UTC, andres-acc commented on src/app/components/footer/footer.component.html
> +    </div>
Check if you really need the `elements-container` wrapper 

```suggestion
      <span class="logo-wolox"></span>
      <div class="social-media">
        <span class="linked-in social-icon"></span>
        <span class="social-text">Conecta con nostros</span>
      </div>
```

2023-03-22 18:24 UTC, andres-acc commented on src/app/components/footer/footer.component.html
> +      <span class="logo-wolox"></span>
Why don't use an `<img />`?

2023-03-22 18:24 UTC, andres-acc commented on src/app/components/footer/footer.component.scss
> +  bottom: 0%;
```suggestion
  bottom: 0;
```

2023-03-22 18:24 UTC, andres-acc commented on src/app/components/footer/footer.component.scss
> +  .floating-images {
```suggestion
  .floating-image {
```

2023-03-22 18:24 UTC, andres-acc commented on src/app/components/footer/footer.component.scss
> +}
Use the scss nesting structure.

2023-03-22 19:55 UTC, miguelhenaoa reviewed
Great job, review the Andres comments

2023-03-22 19:55 UTC, miguelhenaoa commented on src/app/components/footer/footer.component.html
> +        <span class="social-text">Conecta con nostros</span>
Typo, `Conecta con nosotros`

2023-03-23 19:15 UTC, andres-acc approved these changes
Well done 👍

2023-03-23 19:15 UTC, merged