Feat/aa/pagination controls layout
andres-acc/rick-and-morty-w-challenge pull request #9
Opened 2023-02-24 20:46 UTC by andres-acc

## Summary
* Add paginator component

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/102995236/221288028-c7ada7ef-b22a-4adb-869e-4a1650d527f7.gif)

## [Trello Card ](https://trello.com/c/Lqnsm4is)

2023-02-25 02:04 UTC, joacomiguens commented on src/app/components/paginator/paginator.component.ts
> +          ...pagesArray.splice(pagesArray.length - 2, pagesArray.length)
maybe you could assign this to a const and use that const

2023-02-25 02:05 UTC, joacomiguens commented on src/app/components/paginator/paginator.component.ts
> +  goToPageFromArrow(arrow: 'left' | 'right'): void {
```suggestion
  goToPageFromArrow(go: 'back' | 'foward'): void {
```

2023-03-13 16:08 UTC, miguelhenaoa requested changes

2023-03-13 16:08 UTC, miguelhenaoa commented on src/app/components/paginator/page-button/page-button.component.scss
> +}
I think that we can refactor this code 
```suggestion
.left::after {
  @include arrow;
  transform: rotate(225deg);
}
```

2023-03-13 16:08 UTC, miguelhenaoa commented on src/app/components/paginator/page-button/page-button.component.scss
> +}
Same here

2023-03-13 16:08 UTC, miguelhenaoa commented on src/app/components/paginator/page-button/page-button.component.scss
> +}
Same here

2023-03-13 16:08 UTC, miguelhenaoa commented on src/app/components/paginator/paginator.component.html
> +    [current]="page === currentPage"
Maybe we can move this validations to TS file

2023-03-13 16:08 UTC, miguelhenaoa commented on src/app/components/paginator/paginator.component.ts
> +  @Output() gotToPageEvent = new EventEmitter<number>();
Fix typo `goToPageEvent`

2023-03-13 16:08 UTC, miguelhenaoa commented on src/app/components/paginator/paginator.component.ts
> +    }
We can refactor this code
```suggestion
    const newPage = go === 'left' ? this.currentPage - 1 : this.currentPage + 1;
    this.gotToPageEvent.emit(newPage);
    this.definePagesButtons(newPage);
```

2023-03-14 19:58 UTC, miguelhenaoa approved these changes
LGTM!

2023-03-16 20:20 UTC, merged